### ISSUE TITLE
网页打不开, 一直卡在jquery.get

### ISSUE THREAD

**Issue by vachelyang** [suntong/lang#1]
我下载demo:  lang/lang/Charts/ECharts/echarts_LoadCSV_1.html 
然后在本地用chrome打不开, 一直在loading界面. 请问需要其他步骤吗. 谢谢

![image](https://user-images.githubusercontent.com/6931289/35554522-e99c1616-05d6-11e8-92a3-ee340d33888d.png)

检查网页, 发现会报错
jquery.js:9203 Failed to load file:///G:/hcharts_study/lang-master/lang/Charts/ECharts/echarts_LoadCSV.csv: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

![image](https://user-images.githubusercontent.com/6931289/35554769-d61e9ad6-05d7-11e8-9b15-fe1a6b511a9a.png)

**Comment by vachelyang** [comment]
浏览器不能做到 load 本地文件，除非开 server。这是浏览器的安全机制决定的
https://github.com/ecomfe/echarts/issues/4834

**Comment by suntong** [comment]
Oh, yeah, I tested on the server, not local.

**Comment by vachelyang** [comment]
在浏览器中添加属性 --allow-file-access-from-files --allow-http-access-from-files --disable-web-security
